### ISSUE TITLE
MacOS installation experience

### ISSUE THREAD

**Issue by sbliven** [dfeich/emacs-course-and-config#1]
First, I started with Aquamacs 3.5, which is supposed to have nice MacOS integration. Errors:
```
Error (use-package): Failed to install paradox: Package ‘spinner-1.7.3’ is unavailable
Error (use-package): Cannot load paradox
Error (use-package): Failed to install flycheck-package: Package ‘let-alist-1.0.6’ is unavailable
Error (use-package): Cannot load flycheck-package
Error (use-package): Failed to install org-super-agenda: Package ‘emacs-26.1’ is unavailable
Error (use-package): Cannot load org-super-agenda
Error (use-package): Failed to install jupyter: Package ‘emacs-26’ is unavailable
Error (use-package): Cannot load jupyter
Warning (initialization): An error occurred while loading ‘/Users/bliven_s/.emacs.d/init.el’:

File error: Cannot open load file, No such file or directory, ob-jupyter

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Aquamacs is built on GNU Emacs 25.3.50.1. I'm not sure how old that is, but it looks like some packages no longer support it. Would it be straightforward to use emacs-25 compatible packages?

Next, I tried emacs 26.3 and got the following:
```
Symbol's function definition is void: tool-bar-mode
```

I wonder if this configuration should also have some novice-friendly options set (e.g. xterm-mouse-mode).

**Comment by dfeich** [comment]
The problem you see "Package ‘spinner-1.7.3’ is unavailable" is most probably due to the fact that the gpg keys for the GNU ELPA package repository have changed. While most packages come from the MELPA repository, spinner is one of the few ones that come from GNU ELPA, so I have seen this before. Was there no message about connection problems?

In this case it is necessary to import the new GNU ELPA gpg key:

    gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40

(e.g. refer to this link https://metaredux.com/posts/2019/12/09/dealing-with-expired-elpa-gpg-keys.html). Make sure that the path is correct for your installation.

Anyhow... I need to provide a better installer instead on relying on the installations done through the `use-package`configuration mechanisms: https://github.com/dfeich/emacs-course/issues/1

About `xterm-mouse-mode`: The configuration in this repo is for running emacs as an X application, which actually is the way to benefit from all features that emacs can offer for a personal productivity environment, i.e. graphics, reading PDFs, etc. So, this config is not what you want to put on some remote terminal only host, but it is one for your "home"-system. Working on remote systems is most efficiently done by using Emacs' TRAMP functionality that allows it to transparently work on remote nodes through SSH. I almost never start emacs on a remote system while continually using my local emacs to work on all kinds of files and directories on the remote systems.

But there are other novice-friendly settings that may make it easier for beginners (e.g. currently I turned off the symbol menu bar on the top). Thanks, I am glad for feedback that helps me to understand the problems into which relatively new users can run.

**Comment by sbliven** [comment]
I got it working with the emacs app (`brew cask install emacs`)

**Comment by dfeich** [comment]
Ok, great. Since I do not run on a Mac, this kind of information is useful. Maybe there's some Mac specific Emacs pages around I could point people to. I expect that there's a number of Mac specific optimizations that can be made.
